filebeat.prospectors:
  - type: log
    paths:
      - /var/lib/docker/containers/*/*.log
    fields:
      logzio_codec: json
      token: ${LOGZIO_TOKEN}
      type: docker_logs
    fields_under_root: true
    processors:
     - add_cloud_metadata: ~
     - add_docker_metadata: ~
     - drop_event:
         when:
           or:
             # Drop noisiest Rancher logs, we have the last 50MB on the hosts anyway
             - contains:
                 docker.container.name: "r-ipsec-ipsec-router"
             - and:
                 - contains:
                     docker.container.name: "r-scheduler-scheduler"
                 - contains:
                     message: "Updating resource pool"
  - type: log
    paths:
      # This seems to capture everything of interest on RancherOS
      - /var/log/syslog
    fields:
      logzio_codec: plain
      token: ${LOGZIO_TOKEN}
      type: system_logs
    fields_under_root: true
    processors:
     - add_cloud_metadata: ~

logging.level: warning

output.logstash:
  hosts: ["listener-eu.logz.io:5015"]
  ssl.certificate_authorities: ['/usr/share/filebeat/Logzio_CA_Root.crt']
